### ISSUE TITLE
A fucking working example? 

### ISSUE THREAD

**Issue by ally9335** [sei-protocol/sei-cosmos#232]
None of the examples, neither here, in JS, works. There's barely any documentation. In the documantion nothing works again. At npmjs.org -- nothing works! 

There's no example for backend (NodeJs), not the browser, either.

What the fuck works here at all?

Nobody has addressed a dozen of issues on github for the last months.

Is this a project or a piece of shit?  

@LCyson  @BrandonWeng  @udpatil 

---

I need a WORKING EXAMPLE for **NodeJS** (not Browser) or for Golang that simply fucking sends a tx provided a private key or seed-phrase, the target address and amount. For sei (native asset), and for a token on Sei network.

**Comment by philipsu522** [comment]
Answered https://github.com/sei-protocol/sei-chain/issues/737#issuecomment-1534883994
